// <auto-generated>
/*
 * Copyright 2026 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// ContentTooLargeProblemDetails
    /// </summary>
    public partial class ContentTooLargeProblemDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContentTooLargeProblemDetails" /> class.
        /// </summary>
        /// <param name="maxContentLength">If known the remaining content length in bytes that can be sent to the server. If not known, this property will be null.</param>
        /// <param name="type">A URI reference [RFC3986] that identifies the problem type.</param>
        /// <param name="title">A short, human-readable summary of the problem type.</param>
        /// <param name="status">The HTTP status code for this occurrence of the problem.</param>
        /// <param name="detail">A human-readable explanation specific to this occurrence of the problem.</param>
        /// <param name="instance">A URI reference that identifies the specific occurrence of the problem.</param>
        [JsonConstructor]
        public ContentTooLargeProblemDetails(Option<long?> maxContentLength = default, Option<string?> type = default, Option<string?> title = default, Option<int?> status = default, Option<string?> detail = default, Option<string?> instance = default)
        {
            MaxContentLengthOption = maxContentLength;
            TypeOption = type;
            TitleOption = title;
            StatusOption = status;
            DetailOption = detail;
            InstanceOption = instance;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of MaxContentLength
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> MaxContentLengthOption { get; private set; }

        /// <summary>
        /// If known the remaining content length in bytes that can be sent to the server. If not known, this property will be null.
        /// </summary>
        /// <value>If known the remaining content length in bytes that can be sent to the server. If not known, this property will be null.</value>
        [JsonPropertyName("maxContentLength")]
        public long? MaxContentLength { get { return this.MaxContentLengthOption.Value; } set { this.MaxContentLengthOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// A URI reference [RFC3986] that identifies the problem type.
        /// </summary>
        /// <value>A URI reference [RFC3986] that identifies the problem type.</value>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// </summary>
        /// <value>A short, human-readable summary of the problem type.</value>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption.Value; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> StatusOption { get; private set; }

        /// <summary>
        /// The HTTP status code for this occurrence of the problem.
        /// </summary>
        /// <value>The HTTP status code for this occurrence of the problem.</value>
        [JsonPropertyName("status")]
        public int? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Detail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DetailOption { get; private set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        /// <value>A human-readable explanation specific to this occurrence of the problem.</value>
        [JsonPropertyName("detail")]
        public string? Detail { get { return this.DetailOption.Value; } set { this.DetailOption = new(value); } }

        /// <summary>
        /// Used to track the state of Instance
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceOption { get; private set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// </summary>
        /// <value>A URI reference that identifies the specific occurrence of the problem.</value>
        [JsonPropertyName("instance")]
        public string? Instance { get { return this.InstanceOption.Value; } set { this.InstanceOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContentTooLargeProblemDetails {\n");
            sb.Append("  MaxContentLength: ").Append(MaxContentLength).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("  Instance: ").Append(Instance).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ContentTooLargeProblemDetails" />
    /// </summary>
    public class ContentTooLargeProblemDetailsJsonConverter : JsonConverter<ContentTooLargeProblemDetails>
    {
        /// <summary>
        /// Deserializes json to <see cref="ContentTooLargeProblemDetails" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ContentTooLargeProblemDetails Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> maxContentLength = default;
            Option<string?> type = default;
            Option<string?> title = default;
            Option<int?> status = default;
            Option<string?> detail = default;
            Option<string?> instance = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "maxContentLength":
                            maxContentLength = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            status = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "detail":
                            detail = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instance":
                            instance = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ContentTooLargeProblemDetails(maxContentLength, type, title, status, detail, instance);
        }

        /// <summary>
        /// Serializes a <see cref="ContentTooLargeProblemDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contentTooLargeProblemDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ContentTooLargeProblemDetails contentTooLargeProblemDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, contentTooLargeProblemDetails, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ContentTooLargeProblemDetails" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contentTooLargeProblemDetails"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ContentTooLargeProblemDetails contentTooLargeProblemDetails, JsonSerializerOptions jsonSerializerOptions)
        {
            if (contentTooLargeProblemDetails.MaxContentLengthOption.IsSet)
                if (contentTooLargeProblemDetails.MaxContentLengthOption.Value != null)
                    writer.WriteNumber("maxContentLength", contentTooLargeProblemDetails.MaxContentLengthOption.Value!.Value);
                else
                    writer.WriteNull("maxContentLength");

            if (contentTooLargeProblemDetails.TypeOption.IsSet)
                if (contentTooLargeProblemDetails.TypeOption.Value != null)
                    writer.WriteString("type", contentTooLargeProblemDetails.Type);
                else
                    writer.WriteNull("type");

            if (contentTooLargeProblemDetails.TitleOption.IsSet)
                if (contentTooLargeProblemDetails.TitleOption.Value != null)
                    writer.WriteString("title", contentTooLargeProblemDetails.Title);
                else
                    writer.WriteNull("title");

            if (contentTooLargeProblemDetails.StatusOption.IsSet)
                if (contentTooLargeProblemDetails.StatusOption.Value != null)
                    writer.WriteNumber("status", contentTooLargeProblemDetails.StatusOption.Value!.Value);
                else
                    writer.WriteNull("status");

            if (contentTooLargeProblemDetails.DetailOption.IsSet)
                if (contentTooLargeProblemDetails.DetailOption.Value != null)
                    writer.WriteString("detail", contentTooLargeProblemDetails.Detail);
                else
                    writer.WriteNull("detail");

            if (contentTooLargeProblemDetails.InstanceOption.IsSet)
                if (contentTooLargeProblemDetails.InstanceOption.Value != null)
                    writer.WriteString("instance", contentTooLargeProblemDetails.Instance);
                else
                    writer.WriteNull("instance");
        }
    }

    /// <summary>
    /// The ContentTooLargeProblemDetailsSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ContentTooLargeProblemDetails))]
    public partial class ContentTooLargeProblemDetailsSerializationContext : JsonSerializerContext { }
}
