// <auto-generated>
/*
 * Copyright 2026 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// CreateInboundFileSetRequest
    /// </summary>
    public partial class CreateInboundFileSetRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateInboundFileSetRequest" /> class.
        /// </summary>
        /// <param name="type">The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.  The tuple type, revision and period should always be unique.</param>
        /// <param name="revision">A revision number for the file set that is incremented for every retry or redelivery. The tuple type, revision and period should always be unique.</param>
        /// <param name="files">The files associated with the file set.</param>
        /// <param name="period">The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa. The tuple type, revision and period should always be unique.</param>
        [JsonConstructor]
        public CreateInboundFileSetRequest(string type, int revision, Option<List<FileInfo>?> files = default, Option<DateOnly?> period = default)
        {
            Type = type;
            Revision = revision;
            FilesOption = files;
            PeriodOption = period;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.  The tuple type, revision and period should always be unique.
        /// </summary>
        /// <value>The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.  The tuple type, revision and period should always be unique.</value>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// A revision number for the file set that is incremented for every retry or redelivery. The tuple type, revision and period should always be unique.
        /// </summary>
        /// <value>A revision number for the file set that is incremented for every retry or redelivery. The tuple type, revision and period should always be unique.</value>
        [JsonPropertyName("revision")]
        public int Revision { get; set; }

        /// <summary>
        /// Used to track the state of Files
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<FileInfo>?> FilesOption { get; private set; }

        /// <summary>
        /// The files associated with the file set.
        /// </summary>
        /// <value>The files associated with the file set.</value>
        [JsonPropertyName("files")]
        public List<FileInfo>? Files { get { return this.FilesOption.Value; } set { this.FilesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Period
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> PeriodOption { get; private set; }

        /// <summary>
        /// The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa. The tuple type, revision and period should always be unique.
        /// </summary>
        /// <value>The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa. The tuple type, revision and period should always be unique.</value>
        /* <example>Wed Apr 28 00:00:00 UTC 2021</example> */
        [JsonPropertyName("period")]
        public DateOnly? Period { get { return this.PeriodOption.Value; } set { this.PeriodOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateInboundFileSetRequest {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateInboundFileSetRequest" />
    /// </summary>
    public class CreateInboundFileSetRequestJsonConverter : JsonConverter<CreateInboundFileSetRequest>
    {
        /// <summary>
        /// The format to use to serialize Period
        /// </summary>
        public static string PeriodFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="CreateInboundFileSetRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateInboundFileSetRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<int?> revision = default;
            Option<List<FileInfo>?> files = default;
            Option<DateOnly?> period = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "revision":
                            revision = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "files":
                            files = new Option<List<FileInfo>?>(JsonSerializer.Deserialize<List<FileInfo>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "period":
                            period = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class CreateInboundFileSetRequest.", nameof(type));

            if (!revision.IsSet)
                throw new ArgumentException("Property is required for class CreateInboundFileSetRequest.", nameof(revision));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class CreateInboundFileSetRequest.");

            if (revision.IsSet && revision.Value == null)
                throw new ArgumentNullException(nameof(revision), "Property is not nullable for class CreateInboundFileSetRequest.");

            return new CreateInboundFileSetRequest(type.Value!, revision.Value!.Value!, files, period);
        }

        /// <summary>
        /// Serializes a <see cref="CreateInboundFileSetRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createInboundFileSetRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateInboundFileSetRequest createInboundFileSetRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createInboundFileSetRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateInboundFileSetRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createInboundFileSetRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateInboundFileSetRequest createInboundFileSetRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createInboundFileSetRequest.Type == null)
                throw new ArgumentNullException(nameof(createInboundFileSetRequest.Type), "Property is required for class CreateInboundFileSetRequest.");

            writer.WriteString("type", createInboundFileSetRequest.Type);

            writer.WriteNumber("revision", createInboundFileSetRequest.Revision);

            if (createInboundFileSetRequest.FilesOption.IsSet)
                if (createInboundFileSetRequest.FilesOption.Value != null)
                {
                    writer.WritePropertyName("files");
                    JsonSerializer.Serialize(writer, createInboundFileSetRequest.Files, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("files");
            if (createInboundFileSetRequest.PeriodOption.IsSet)
                if (createInboundFileSetRequest.PeriodOption.Value != null)
                    writer.WriteString("period", createInboundFileSetRequest.PeriodOption.Value!.Value.ToString(PeriodFormat));
                else
                    writer.WriteNull("period");
        }
    }

    /// <summary>
    /// The CreateInboundFileSetRequestSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(CreateInboundFileSetRequest))]
    public partial class CreateInboundFileSetRequestSerializationContext : JsonSerializerContext { }
}
