// <auto-generated>
/*
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// The payload for the webhooks for the outbound file sets.
    /// </summary>
    public partial class FileSetsOutboundFileSetWebhookPayload
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileSetsOutboundFileSetWebhookPayload" /> class.
        /// </summary>
        /// <param name="callbackName">callbackName</param>
        /// <param name="eventId">Uniek Id voor deze callback.</param>
        /// <param name="timestamp">Het tijdstip van het event, in UTC.</param>
        /// <param name="fileSetId">The Id of the file set to which this callback pertains.</param>
        /// <param name="oldStatus">oldStatus</param>
        /// <param name="newStatus">newStatus</param>
        [JsonConstructor]
        public FileSetsOutboundFileSetWebhookPayload(string callbackName, Guid eventId, DateTime timestamp, Option<Guid?> fileSetId = default, Option<OutboundFileSetState?> oldStatus = default, Option<OutboundFileSetState?> newStatus = default)
        {
            CallbackName = callbackName;
            EventId = eventId;
            Timestamp = timestamp;
            FileSetIdOption = fileSetId;
            OldStatusOption = oldStatus;
            NewStatusOption = newStatus;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OldStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OutboundFileSetState?> OldStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets OldStatus
        /// </summary>
        [JsonPropertyName("oldStatus")]
        public OutboundFileSetState? OldStatus { get { return this.OldStatusOption; } set { this.OldStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OutboundFileSetState?> NewStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewStatus
        /// </summary>
        [JsonPropertyName("newStatus")]
        public OutboundFileSetState? NewStatus { get { return this.NewStatusOption; } set { this.NewStatusOption = new(value); } }

        /// <summary>
        /// Gets or Sets CallbackName
        /// </summary>
        [JsonPropertyName("callbackName")]
        public string CallbackName { get; }

        /// <summary>
        /// Uniek Id voor deze callback.
        /// </summary>
        /// <value>Uniek Id voor deze callback.</value>
        [JsonPropertyName("eventId")]
        public Guid EventId { get; set; }

        /// <summary>
        /// Het tijdstip van het event, in UTC.
        /// </summary>
        /// <value>Het tijdstip van het event, in UTC.</value>
        /* <example>2021-04-28T12:34:45Z</example> */
        [JsonPropertyName("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Used to track the state of FileSetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> FileSetIdOption { get; private set; }

        /// <summary>
        /// The Id of the file set to which this callback pertains.
        /// </summary>
        /// <value>The Id of the file set to which this callback pertains.</value>
        [JsonPropertyName("fileSetId")]
        public Guid? FileSetId { get { return this.FileSetIdOption; } set { this.FileSetIdOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileSetsOutboundFileSetWebhookPayload {\n");
            sb.Append("  CallbackName: ").Append(CallbackName).Append("\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  FileSetId: ").Append(FileSetId).Append("\n");
            sb.Append("  OldStatus: ").Append(OldStatus).Append("\n");
            sb.Append("  NewStatus: ").Append(NewStatus).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FileSetsOutboundFileSetWebhookPayload" />
    /// </summary>
    public class FileSetsOutboundFileSetWebhookPayloadJsonConverter : JsonConverter<FileSetsOutboundFileSetWebhookPayload>
    {
        /// <summary>
        /// The format to use to serialize Timestamp
        /// </summary>
        public static string TimestampFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ssZ";

        /// <summary>
        /// Deserializes json to <see cref="FileSetsOutboundFileSetWebhookPayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FileSetsOutboundFileSetWebhookPayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> callbackName = default;
            Option<Guid?> eventId = default;
            Option<DateTime?> timestamp = default;
            Option<Guid?> fileSetId = default;
            Option<OutboundFileSetState?> oldStatus = default;
            Option<OutboundFileSetState?> newStatus = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "callbackName":
                            callbackName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "eventId":
                            eventId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "timestamp":
                            timestamp = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "fileSetId":
                            fileSetId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "oldStatus":
                            string? oldStatusRawValue = utf8JsonReader.GetString();
                            if (oldStatusRawValue != null)
                                oldStatus = new Option<OutboundFileSetState?>(OutboundFileSetStateValueConverter.FromStringOrDefault(oldStatusRawValue));
                            break;
                        case "newStatus":
                            string? newStatusRawValue = utf8JsonReader.GetString();
                            if (newStatusRawValue != null)
                                newStatus = new Option<OutboundFileSetState?>(OutboundFileSetStateValueConverter.FromStringOrDefault(newStatusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!callbackName.IsSet)
                throw new ArgumentException("Property is required for class FileSetsOutboundFileSetWebhookPayload.", nameof(callbackName));

            if (!eventId.IsSet)
                throw new ArgumentException("Property is required for class FileSetsOutboundFileSetWebhookPayload.", nameof(eventId));

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class FileSetsOutboundFileSetWebhookPayload.", nameof(timestamp));

            if (callbackName.IsSet && callbackName.Value == null)
                throw new ArgumentNullException(nameof(callbackName), "Property is not nullable for class FileSetsOutboundFileSetWebhookPayload.");

            if (eventId.IsSet && eventId.Value == null)
                throw new ArgumentNullException(nameof(eventId), "Property is not nullable for class FileSetsOutboundFileSetWebhookPayload.");

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class FileSetsOutboundFileSetWebhookPayload.");

            if (fileSetId.IsSet && fileSetId.Value == null)
                throw new ArgumentNullException(nameof(fileSetId), "Property is not nullable for class FileSetsOutboundFileSetWebhookPayload.");

            if (oldStatus.IsSet && oldStatus.Value == null)
                throw new ArgumentNullException(nameof(oldStatus), "Property is not nullable for class FileSetsOutboundFileSetWebhookPayload.");

            if (newStatus.IsSet && newStatus.Value == null)
                throw new ArgumentNullException(nameof(newStatus), "Property is not nullable for class FileSetsOutboundFileSetWebhookPayload.");

            return new FileSetsOutboundFileSetWebhookPayload(callbackName.Value!, eventId.Value!.Value!, timestamp.Value!.Value!, fileSetId, oldStatus, newStatus);
        }

        /// <summary>
        /// Serializes a <see cref="FileSetsOutboundFileSetWebhookPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileSetsOutboundFileSetWebhookPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FileSetsOutboundFileSetWebhookPayload fileSetsOutboundFileSetWebhookPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fileSetsOutboundFileSetWebhookPayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FileSetsOutboundFileSetWebhookPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileSetsOutboundFileSetWebhookPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FileSetsOutboundFileSetWebhookPayload fileSetsOutboundFileSetWebhookPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fileSetsOutboundFileSetWebhookPayload.CallbackName == null)
                throw new ArgumentNullException(nameof(fileSetsOutboundFileSetWebhookPayload.CallbackName), "Property is required for class FileSetsOutboundFileSetWebhookPayload.");

            writer.WriteString("callbackName", fileSetsOutboundFileSetWebhookPayload.CallbackName);

            writer.WriteString("eventId", fileSetsOutboundFileSetWebhookPayload.EventId);

            writer.WriteString("timestamp", fileSetsOutboundFileSetWebhookPayload.Timestamp.ToString(TimestampFormat));

            if (fileSetsOutboundFileSetWebhookPayload.FileSetIdOption.IsSet)
                writer.WriteString("fileSetId", fileSetsOutboundFileSetWebhookPayload.FileSetIdOption.Value!.Value);

            if (fileSetsOutboundFileSetWebhookPayload.OldStatusOption.IsSet)
            {
                var oldStatusRawValue = OutboundFileSetStateValueConverter.ToJsonValue(fileSetsOutboundFileSetWebhookPayload.OldStatus!.Value);
                writer.WriteString("oldStatus", oldStatusRawValue);
            }
            if (fileSetsOutboundFileSetWebhookPayload.NewStatusOption.IsSet)
            {
                var newStatusRawValue = OutboundFileSetStateValueConverter.ToJsonValue(fileSetsOutboundFileSetWebhookPayload.NewStatus!.Value);
                writer.WriteString("newStatus", newStatusRawValue);
            }
        }
    }

    /// <summary>
    /// The FileSetsOutboundFileSetWebhookPayloadSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(FileSetsOutboundFileSetWebhookPayload))]
    public partial class FileSetsOutboundFileSetWebhookPayloadSerializationContext : JsonSerializerContext { }
}
