// <auto-generated>
/*
 * Copyright 2026 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// Defines FunderingTechnischHerstelType
    /// </summary>
    public enum FunderingTechnischHerstelType
    {
        /// <summary>
        /// Enum OnbekendTechnischHerstelType for value: onbekendTechnischHerstelType
        /// </summary>
        OnbekendTechnischHerstelType,

        /// <summary>
        /// Enum Tafelconstructie for value: tafelconstructie
        /// </summary>
        Tafelconstructie,

        /// <summary>
        /// Enum BetonbalkOverPaal for value: betonbalkOverPaal
        /// </summary>
        BetonbalkOverPaal,

        /// <summary>
        /// Enum Paalkopverlaging for value: paalkopverlaging
        /// </summary>
        Paalkopverlaging,

        /// <summary>
        /// Enum PaalInWandMethode for value: paalInWandMethode
        /// </summary>
        PaalInWandMethode,

        /// <summary>
        /// Enum GrondinjectieOfVerbetering for value: grondinjectieOfVerbetering
        /// </summary>
        GrondinjectieOfVerbetering
    }

    /// <summary>
    /// Converts <see cref="FunderingTechnischHerstelType"/> to and from the JSON value
    /// </summary>
    public static class FunderingTechnischHerstelTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="FunderingTechnischHerstelType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FunderingTechnischHerstelType FromString(string value)
        {
            if (value.Equals("onbekendTechnischHerstelType"))
                return FunderingTechnischHerstelType.OnbekendTechnischHerstelType;

            if (value.Equals("tafelconstructie"))
                return FunderingTechnischHerstelType.Tafelconstructie;

            if (value.Equals("betonbalkOverPaal"))
                return FunderingTechnischHerstelType.BetonbalkOverPaal;

            if (value.Equals("paalkopverlaging"))
                return FunderingTechnischHerstelType.Paalkopverlaging;

            if (value.Equals("paalInWandMethode"))
                return FunderingTechnischHerstelType.PaalInWandMethode;

            if (value.Equals("grondinjectieOfVerbetering"))
                return FunderingTechnischHerstelType.GrondinjectieOfVerbetering;

            throw new NotImplementedException($"Could not convert value to type FunderingTechnischHerstelType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="FunderingTechnischHerstelType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FunderingTechnischHerstelType? FromStringOrDefault(string value)
        {
            if (value.Equals("onbekendTechnischHerstelType"))
                return FunderingTechnischHerstelType.OnbekendTechnischHerstelType;

            if (value.Equals("tafelconstructie"))
                return FunderingTechnischHerstelType.Tafelconstructie;

            if (value.Equals("betonbalkOverPaal"))
                return FunderingTechnischHerstelType.BetonbalkOverPaal;

            if (value.Equals("paalkopverlaging"))
                return FunderingTechnischHerstelType.Paalkopverlaging;

            if (value.Equals("paalInWandMethode"))
                return FunderingTechnischHerstelType.PaalInWandMethode;

            if (value.Equals("grondinjectieOfVerbetering"))
                return FunderingTechnischHerstelType.GrondinjectieOfVerbetering;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FunderingTechnischHerstelType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(FunderingTechnischHerstelType value)
        {
            if (value == FunderingTechnischHerstelType.OnbekendTechnischHerstelType)
                return "onbekendTechnischHerstelType";

            if (value == FunderingTechnischHerstelType.Tafelconstructie)
                return "tafelconstructie";

            if (value == FunderingTechnischHerstelType.BetonbalkOverPaal)
                return "betonbalkOverPaal";

            if (value == FunderingTechnischHerstelType.Paalkopverlaging)
                return "paalkopverlaging";

            if (value == FunderingTechnischHerstelType.PaalInWandMethode)
                return "paalInWandMethode";

            if (value == FunderingTechnischHerstelType.GrondinjectieOfVerbetering)
                return "grondinjectieOfVerbetering";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FunderingTechnischHerstelType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class FunderingTechnischHerstelTypeJsonConverter : JsonConverter<FunderingTechnischHerstelType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override FunderingTechnischHerstelType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            FunderingTechnischHerstelType? result = rawValue == null
                ? null
                : FunderingTechnischHerstelTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the FunderingTechnischHerstelType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="funderingTechnischHerstelType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, FunderingTechnischHerstelType funderingTechnischHerstelType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(FunderingTechnischHerstelTypeValueConverter.ToJsonValue(funderingTechnischHerstelType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FunderingTechnischHerstelType"/>
    /// </summary>
    public class FunderingTechnischHerstelTypeNullableJsonConverter : JsonConverter<FunderingTechnischHerstelType?>
    {
        /// <summary>
        /// Returns a FunderingTechnischHerstelType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override FunderingTechnischHerstelType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            FunderingTechnischHerstelType? result = rawValue == null
                ? null
                : FunderingTechnischHerstelTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the FunderingTechnischHerstelType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="funderingTechnischHerstelType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, FunderingTechnischHerstelType? funderingTechnischHerstelType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(funderingTechnischHerstelType.HasValue ? FunderingTechnischHerstelTypeValueConverter.ToJsonValue(funderingTechnischHerstelType.Value).ToString() : "null");
        }
    }


    /// <summary>
    /// The FunderingTechnischHerstelTypeSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(FunderingTechnischHerstelType))]
    public partial class FunderingTechnischHerstelTypeSerializationContext : JsonSerializerContext { }
}
