// <auto-generated>
/*
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// Inbound file set states.  | Value | Description | | - -- | - -- | | &#x60;created&#x60; | File set has just been created and is waiting for the files to be uploaded. | | &#x60;uploading&#x60; | File set is being uploaded, but not all files have been uploaded yet. | | &#x60;verifying&#x60; | File set has been fully uploaded and has been confirmed, the file set is in the process of being verified. | | &#x60;accepted&#x60; | File set has been fully uploaded and has been confirmed, the file set has been verified and is ready for processing. | | &#x60;accepted_with_warnings&#x60; | File set has been fully uploaded and has been confirmed, the file set has been verified and is ready for processing, but there were some warnings during the verification process. | | &#x60;rejected&#x60; | File set has been fully uploaded and has been confirmed, but the file set has been rejected during the verification process. There will be errors in the file set that need to be fixed before it can be processed. | | &#x60;expired&#x60; | File set has expired and all its uploaded contents have been deleted. |
    /// </summary>
    /// <value>Inbound file set states.  | Value | Description | | - -- | - -- | | &#x60;created&#x60; | File set has just been created and is waiting for the files to be uploaded. | | &#x60;uploading&#x60; | File set is being uploaded, but not all files have been uploaded yet. | | &#x60;verifying&#x60; | File set has been fully uploaded and has been confirmed, the file set is in the process of being verified. | | &#x60;accepted&#x60; | File set has been fully uploaded and has been confirmed, the file set has been verified and is ready for processing. | | &#x60;accepted_with_warnings&#x60; | File set has been fully uploaded and has been confirmed, the file set has been verified and is ready for processing, but there were some warnings during the verification process. | | &#x60;rejected&#x60; | File set has been fully uploaded and has been confirmed, but the file set has been rejected during the verification process. There will be errors in the file set that need to be fixed before it can be processed. | | &#x60;expired&#x60; | File set has expired and all its uploaded contents have been deleted. |</value>
    public enum InboundFileSetState
    {
        /// <summary>
        /// Enum Created for value: created
        /// </summary>
        Created,

        /// <summary>
        /// Enum Uploading for value: uploading
        /// </summary>
        Uploading,

        /// <summary>
        /// Enum Verifying for value: verifying
        /// </summary>
        Verifying,

        /// <summary>
        /// Enum Accepted for value: accepted
        /// </summary>
        Accepted,

        /// <summary>
        /// Enum AcceptedWithWarnings for value: accepted_with_warnings
        /// </summary>
        AcceptedWithWarnings,

        /// <summary>
        /// Enum Rejected for value: rejected
        /// </summary>
        Rejected,

        /// <summary>
        /// Enum Expired for value: expired
        /// </summary>
        Expired
    }

    /// <summary>
    /// Converts <see cref="InboundFileSetState"/> to and from the JSON value
    /// </summary>
    public static class InboundFileSetStateValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="InboundFileSetState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static InboundFileSetState FromString(string value)
        {
            if (value.Equals("created"))
                return InboundFileSetState.Created;

            if (value.Equals("uploading"))
                return InboundFileSetState.Uploading;

            if (value.Equals("verifying"))
                return InboundFileSetState.Verifying;

            if (value.Equals("accepted"))
                return InboundFileSetState.Accepted;

            if (value.Equals("accepted_with_warnings"))
                return InboundFileSetState.AcceptedWithWarnings;

            if (value.Equals("rejected"))
                return InboundFileSetState.Rejected;

            if (value.Equals("expired"))
                return InboundFileSetState.Expired;

            throw new NotImplementedException($"Could not convert value to type InboundFileSetState: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="InboundFileSetState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static InboundFileSetState? FromStringOrDefault(string value)
        {
            if (value.Equals("created"))
                return InboundFileSetState.Created;

            if (value.Equals("uploading"))
                return InboundFileSetState.Uploading;

            if (value.Equals("verifying"))
                return InboundFileSetState.Verifying;

            if (value.Equals("accepted"))
                return InboundFileSetState.Accepted;

            if (value.Equals("accepted_with_warnings"))
                return InboundFileSetState.AcceptedWithWarnings;

            if (value.Equals("rejected"))
                return InboundFileSetState.Rejected;

            if (value.Equals("expired"))
                return InboundFileSetState.Expired;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="InboundFileSetState"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(InboundFileSetState value)
        {
            if (value == InboundFileSetState.Created)
                return "created";

            if (value == InboundFileSetState.Uploading)
                return "uploading";

            if (value == InboundFileSetState.Verifying)
                return "verifying";

            if (value == InboundFileSetState.Accepted)
                return "accepted";

            if (value == InboundFileSetState.AcceptedWithWarnings)
                return "accepted_with_warnings";

            if (value == InboundFileSetState.Rejected)
                return "rejected";

            if (value == InboundFileSetState.Expired)
                return "expired";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InboundFileSetState"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class InboundFileSetStateJsonConverter : JsonConverter<InboundFileSetState>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override InboundFileSetState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            InboundFileSetState? result = rawValue == null
                ? null
                : InboundFileSetStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the InboundFileSetState to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundFileSetState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, InboundFileSetState inboundFileSetState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(InboundFileSetStateValueConverter.ToJsonValue(inboundFileSetState).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InboundFileSetState"/>
    /// </summary>
    public class InboundFileSetStateNullableJsonConverter : JsonConverter<InboundFileSetState?>
    {
        /// <summary>
        /// Returns a InboundFileSetState from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override InboundFileSetState? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            InboundFileSetState? result = rawValue == null
                ? null
                : InboundFileSetStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the InboundFileSetState to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundFileSetState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, InboundFileSetState? inboundFileSetState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(inboundFileSetState.HasValue ? InboundFileSetStateValueConverter.ToJsonValue(inboundFileSetState.Value).ToString() : "null");
        }
    }


    /// <summary>
    /// The InboundFileSetStateSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(InboundFileSetState))]
    public partial class InboundFileSetStateSerializationContext : JsonSerializerContext { }
}
