// <auto-generated>
/*
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// Het type authenticatie dat gebruikt wordt voor callbacks. PublicCA is deprecated en wordt uitgefaseerd. Het gebruikte certificaat is beschikbaar op het endpoint GET /v1/callbacks/mtls-certificate.
    /// </summary>
    /// <value>Het type authenticatie dat gebruikt wordt voor callbacks. PublicCA is deprecated en wordt uitgefaseerd. Het gebruikte certificaat is beschikbaar op het endpoint GET /v1/callbacks/mtls-certificate.</value>
    public enum MTLSType
    {
        /// <summary>
        /// Enum None for value: none
        /// </summary>
        None,

        /// <summary>
        /// Enum PublicCA for value: PublicCA
        /// </summary>
        PublicCA,

        /// <summary>
        /// Enum SelfSigned for value: SelfSigned
        /// </summary>
        SelfSigned
    }

    /// <summary>
    /// Converts <see cref="MTLSType"/> to and from the JSON value
    /// </summary>
    public static class MTLSTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="MTLSType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MTLSType FromString(string value)
        {
            if (value.Equals("none"))
                return MTLSType.None;

            if (value.Equals("PublicCA"))
                return MTLSType.PublicCA;

            if (value.Equals("SelfSigned"))
                return MTLSType.SelfSigned;

            throw new NotImplementedException($"Could not convert value to type MTLSType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="MTLSType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MTLSType? FromStringOrDefault(string value)
        {
            if (value.Equals("none"))
                return MTLSType.None;

            if (value.Equals("PublicCA"))
                return MTLSType.PublicCA;

            if (value.Equals("SelfSigned"))
                return MTLSType.SelfSigned;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MTLSType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(MTLSType value)
        {
            if (value == MTLSType.None)
                return "none";

            if (value == MTLSType.PublicCA)
                return "PublicCA";

            if (value == MTLSType.SelfSigned)
                return "SelfSigned";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MTLSType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class MTLSTypeJsonConverter : JsonConverter<MTLSType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MTLSType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MTLSType? result = rawValue == null
                ? null
                : MTLSTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the MTLSType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mTLSType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MTLSType mTLSType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(MTLSTypeValueConverter.ToJsonValue(mTLSType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MTLSType"/>
    /// </summary>
    public class MTLSTypeNullableJsonConverter : JsonConverter<MTLSType?>
    {
        /// <summary>
        /// Returns a MTLSType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override MTLSType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            MTLSType? result = rawValue == null
                ? null
                : MTLSTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the MTLSType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mTLSType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, MTLSType? mTLSType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(mTLSType.HasValue ? MTLSTypeValueConverter.ToJsonValue(mTLSType.Value).ToString() : "null");
        }
    }


    /// <summary>
    /// The MTLSTypeSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(MTLSType))]
    public partial class MTLSTypeSerializationContext : JsonSerializerContext { }
}
