// <auto-generated>
/*
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// Defines OnderhoudStaat
    /// </summary>
    public enum OnderhoudStaat
    {
        /// <summary>
        /// Enum Onbekend for value: onbekend
        /// </summary>
        Onbekend,

        /// <summary>
        /// Enum Slecht for value: slecht
        /// </summary>
        Slecht,

        /// <summary>
        /// Enum Matig for value: matig
        /// </summary>
        Matig,

        /// <summary>
        /// Enum Redelijk for value: redelijk
        /// </summary>
        Redelijk,

        /// <summary>
        /// Enum Goed for value: goed
        /// </summary>
        Goed,

        /// <summary>
        /// Enum NietWaarneembaar for value: nietWaarneembaar
        /// </summary>
        NietWaarneembaar,

        /// <summary>
        /// Enum NietVanToepassing for value: nietVanToepassing
        /// </summary>
        NietVanToepassing
    }

    /// <summary>
    /// Converts <see cref="OnderhoudStaat"/> to and from the JSON value
    /// </summary>
    public static class OnderhoudStaatValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="OnderhoudStaat"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OnderhoudStaat FromString(string value)
        {
            if (value.Equals("onbekend"))
                return OnderhoudStaat.Onbekend;

            if (value.Equals("slecht"))
                return OnderhoudStaat.Slecht;

            if (value.Equals("matig"))
                return OnderhoudStaat.Matig;

            if (value.Equals("redelijk"))
                return OnderhoudStaat.Redelijk;

            if (value.Equals("goed"))
                return OnderhoudStaat.Goed;

            if (value.Equals("nietWaarneembaar"))
                return OnderhoudStaat.NietWaarneembaar;

            if (value.Equals("nietVanToepassing"))
                return OnderhoudStaat.NietVanToepassing;

            throw new NotImplementedException($"Could not convert value to type OnderhoudStaat: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="OnderhoudStaat"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OnderhoudStaat? FromStringOrDefault(string value)
        {
            if (value.Equals("onbekend"))
                return OnderhoudStaat.Onbekend;

            if (value.Equals("slecht"))
                return OnderhoudStaat.Slecht;

            if (value.Equals("matig"))
                return OnderhoudStaat.Matig;

            if (value.Equals("redelijk"))
                return OnderhoudStaat.Redelijk;

            if (value.Equals("goed"))
                return OnderhoudStaat.Goed;

            if (value.Equals("nietWaarneembaar"))
                return OnderhoudStaat.NietWaarneembaar;

            if (value.Equals("nietVanToepassing"))
                return OnderhoudStaat.NietVanToepassing;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OnderhoudStaat"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(OnderhoudStaat value)
        {
            if (value == OnderhoudStaat.Onbekend)
                return "onbekend";

            if (value == OnderhoudStaat.Slecht)
                return "slecht";

            if (value == OnderhoudStaat.Matig)
                return "matig";

            if (value == OnderhoudStaat.Redelijk)
                return "redelijk";

            if (value == OnderhoudStaat.Goed)
                return "goed";

            if (value == OnderhoudStaat.NietWaarneembaar)
                return "nietWaarneembaar";

            if (value == OnderhoudStaat.NietVanToepassing)
                return "nietVanToepassing";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OnderhoudStaat"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class OnderhoudStaatJsonConverter : JsonConverter<OnderhoudStaat>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override OnderhoudStaat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            OnderhoudStaat? result = rawValue == null
                ? null
                : OnderhoudStaatValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the OnderhoudStaat to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="onderhoudStaat"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, OnderhoudStaat onderhoudStaat, JsonSerializerOptions options)
        {
            writer.WriteStringValue(OnderhoudStaatValueConverter.ToJsonValue(onderhoudStaat).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OnderhoudStaat"/>
    /// </summary>
    public class OnderhoudStaatNullableJsonConverter : JsonConverter<OnderhoudStaat?>
    {
        /// <summary>
        /// Returns a OnderhoudStaat from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override OnderhoudStaat? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            OnderhoudStaat? result = rawValue == null
                ? null
                : OnderhoudStaatValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the OnderhoudStaat to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="onderhoudStaat"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, OnderhoudStaat? onderhoudStaat, JsonSerializerOptions options)
        {
            writer.WriteStringValue(onderhoudStaat.HasValue ? OnderhoudStaatValueConverter.ToJsonValue(onderhoudStaat.Value).ToString() : "null");
        }
    }


    /// <summary>
    /// The OnderhoudStaatSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(OnderhoudStaat))]
    public partial class OnderhoudStaatSerializationContext : JsonSerializerContext { }
}
