// <auto-generated>
/*
 * Copyright 2025 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).
 *
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using System.Text.RegularExpressions;
using Calcasa.Api.Client;

namespace Calcasa.Api.Model
{
    /// <summary>
    /// OutboundFileSet
    /// </summary>
    public partial class OutboundFileSet
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OutboundFileSet" /> class.
        /// </summary>
        /// <param name="id">The file set ID, which is a unique identifier for the file set. This ID is used to track and manage the file set throughout its lifecycle. It is generated by the system when the file set is created and is used in API requests to reference the specific file set.</param>
        /// <param name="files">The files associated with the file set.</param>
        /// <param name="createdOn">createdOn</param>
        /// <param name="modifiedOn">modifiedOn</param>
        /// <param name="type">The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.</param>
        /// <param name="revision">A revision number for the file set that is incremented for every retry or redelivery.</param>
        /// <param name="inboundFileSetId">The id of the inbound file set from which this outbound file set originated. This is used to track the relationship between inbound and outbound file sets. The inboundFileSetId and revision combination should be unique for each outbound file set.</param>
        /// <param name="state">state</param>
        /// <param name="expiresAfter">If specified the file set will expire after this date and time. If no appropiate action is taken before this date and time, the file set and all its contents will be deleted.</param>
        /// <param name="period">The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa.</param>
        [JsonConstructor]
        public OutboundFileSet(Guid id, Collection<FileInfo> files, DateTime createdOn, DateTime modifiedOn, string type, int revision, Guid inboundFileSetId, OutboundFileSetState state, Option<DateTime?> expiresAfter = default, Option<DateOnly?> period = default)
        {
            Id = id;
            Files = files;
            CreatedOn = createdOn;
            ModifiedOn = modifiedOn;
            Type = type;
            Revision = revision;
            InboundFileSetId = inboundFileSetId;
            State = state;
            ExpiresAfterOption = expiresAfter;
            PeriodOption = period;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public OutboundFileSetState State { get; set; }

        /// <summary>
        /// The file set ID, which is a unique identifier for the file set. This ID is used to track and manage the file set throughout its lifecycle. It is generated by the system when the file set is created and is used in API requests to reference the specific file set.
        /// </summary>
        /// <value>The file set ID, which is a unique identifier for the file set. This ID is used to track and manage the file set throughout its lifecycle. It is generated by the system when the file set is created and is used in API requests to reference the specific file set.</value>
        [JsonPropertyName("id")]
        public Guid Id { get; }

        /// <summary>
        /// The files associated with the file set.
        /// </summary>
        /// <value>The files associated with the file set.</value>
        [JsonPropertyName("files")]
        public Collection<FileInfo> Files { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        /* <example>2021-04-28T12:34:45Z</example> */
        [JsonPropertyName("createdOn")]
        public DateTime CreatedOn { get; }

        /// <summary>
        /// Gets or Sets ModifiedOn
        /// </summary>
        /* <example>2021-04-28T12:34:45Z</example> */
        [JsonPropertyName("modifiedOn")]
        public DateTime ModifiedOn { get; }

        /// <summary>
        /// The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.
        /// </summary>
        /// <value>The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.</value>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// A revision number for the file set that is incremented for every retry or redelivery.
        /// </summary>
        /// <value>A revision number for the file set that is incremented for every retry or redelivery.</value>
        [JsonPropertyName("revision")]
        public int Revision { get; set; }

        /// <summary>
        /// The id of the inbound file set from which this outbound file set originated. This is used to track the relationship between inbound and outbound file sets. The inboundFileSetId and revision combination should be unique for each outbound file set.
        /// </summary>
        /// <value>The id of the inbound file set from which this outbound file set originated. This is used to track the relationship between inbound and outbound file sets. The inboundFileSetId and revision combination should be unique for each outbound file set.</value>
        [JsonPropertyName("inboundFileSetId")]
        public Guid InboundFileSetId { get; set; }

        /// <summary>
        /// Used to track the state of ExpiresAfter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ExpiresAfterOption { get; }

        /// <summary>
        /// If specified the file set will expire after this date and time. If no appropiate action is taken before this date and time, the file set and all its contents will be deleted.
        /// </summary>
        /// <value>If specified the file set will expire after this date and time. If no appropiate action is taken before this date and time, the file set and all its contents will be deleted.</value>
        /* <example>2021-04-28T12:34:45Z</example> */
        [JsonPropertyName("expiresAfter")]
        public DateTime? ExpiresAfter { get { return this.ExpiresAfterOption; } }

        /// <summary>
        /// Used to track the state of Period
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> PeriodOption { get; private set; }

        /// <summary>
        /// The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa.
        /// </summary>
        /// <value>The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa.</value>
        /* <example>Wed Apr 28 00:00:00 UTC 2021</example> */
        [JsonPropertyName("period")]
        public DateOnly? Period { get { return this.PeriodOption; } set { this.PeriodOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OutboundFileSet {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  ModifiedOn: ").Append(ModifiedOn).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("  InboundFileSetId: ").Append(InboundFileSetId).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  ExpiresAfter: ").Append(ExpiresAfter).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OutboundFileSet" />
    /// </summary>
    public class OutboundFileSetJsonConverter : JsonConverter<OutboundFileSet>
    {
        /// <summary>
        /// The format to use to serialize CreatedOn
        /// </summary>
        public static string CreatedOnFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ssZ";

        /// <summary>
        /// The format to use to serialize ModifiedOn
        /// </summary>
        public static string ModifiedOnFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ssZ";

        /// <summary>
        /// The format to use to serialize ExpiresAfter
        /// </summary>
        public static string ExpiresAfterFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ssZ";

        /// <summary>
        /// The format to use to serialize Period
        /// </summary>
        public static string PeriodFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="OutboundFileSet" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OutboundFileSet Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Collection<FileInfo>?> files = default;
            Option<DateTime?> createdOn = default;
            Option<DateTime?> modifiedOn = default;
            Option<string?> type = default;
            Option<int?> revision = default;
            Option<Guid?> inboundFileSetId = default;
            Option<OutboundFileSetState?> state = default;
            Option<DateTime?> expiresAfter = default;
            Option<DateOnly?> period = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "files":
                            files = new Option<Collection<FileInfo>?>(JsonSerializer.Deserialize<Collection<FileInfo>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "createdOn":
                            createdOn = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "modifiedOn":
                            modifiedOn = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "revision":
                            revision = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "inboundFileSetId":
                            inboundFileSetId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "state":
                            string? stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                                state = new Option<OutboundFileSetState?>(OutboundFileSetStateValueConverter.FromStringOrDefault(stateRawValue));
                            break;
                        case "expiresAfter":
                            expiresAfter = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "period":
                            period = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(id));

            if (!files.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(files));

            if (!createdOn.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(createdOn));

            if (!modifiedOn.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(modifiedOn));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(type));

            if (!revision.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(revision));

            if (!inboundFileSetId.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(inboundFileSetId));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class OutboundFileSet.", nameof(state));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OutboundFileSet.");

            if (files.IsSet && files.Value == null)
                throw new ArgumentNullException(nameof(files), "Property is not nullable for class OutboundFileSet.");

            if (createdOn.IsSet && createdOn.Value == null)
                throw new ArgumentNullException(nameof(createdOn), "Property is not nullable for class OutboundFileSet.");

            if (modifiedOn.IsSet && modifiedOn.Value == null)
                throw new ArgumentNullException(nameof(modifiedOn), "Property is not nullable for class OutboundFileSet.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class OutboundFileSet.");

            if (revision.IsSet && revision.Value == null)
                throw new ArgumentNullException(nameof(revision), "Property is not nullable for class OutboundFileSet.");

            if (inboundFileSetId.IsSet && inboundFileSetId.Value == null)
                throw new ArgumentNullException(nameof(inboundFileSetId), "Property is not nullable for class OutboundFileSet.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class OutboundFileSet.");

            return new OutboundFileSet(id.Value!.Value!, files.Value!, createdOn.Value!.Value!, modifiedOn.Value!.Value!, type.Value!, revision.Value!.Value!, inboundFileSetId.Value!.Value!, state.Value!.Value!, expiresAfter, period);
        }

        /// <summary>
        /// Serializes a <see cref="OutboundFileSet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="outboundFileSet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OutboundFileSet outboundFileSet, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, outboundFileSet, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OutboundFileSet" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="outboundFileSet"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OutboundFileSet outboundFileSet, JsonSerializerOptions jsonSerializerOptions)
        {
            if (outboundFileSet.Files == null)
                throw new ArgumentNullException(nameof(outboundFileSet.Files), "Property is required for class OutboundFileSet.");

            if (outboundFileSet.Type == null)
                throw new ArgumentNullException(nameof(outboundFileSet.Type), "Property is required for class OutboundFileSet.");

            writer.WriteString("id", outboundFileSet.Id);

            writer.WritePropertyName("files");
            JsonSerializer.Serialize(writer, outboundFileSet.Files, jsonSerializerOptions);
            writer.WriteString("createdOn", outboundFileSet.CreatedOn.ToString(CreatedOnFormat));

            writer.WriteString("modifiedOn", outboundFileSet.ModifiedOn.ToString(ModifiedOnFormat));

            writer.WriteString("type", outboundFileSet.Type);

            writer.WriteNumber("revision", outboundFileSet.Revision);

            writer.WriteString("inboundFileSetId", outboundFileSet.InboundFileSetId);

            var stateRawValue = OutboundFileSetStateValueConverter.ToJsonValue(outboundFileSet.State);
            writer.WriteString("state", stateRawValue);

            if (outboundFileSet.ExpiresAfterOption.IsSet)
                if (outboundFileSet.ExpiresAfterOption.Value != null)
                    writer.WriteString("expiresAfter", outboundFileSet.ExpiresAfterOption.Value!.Value.ToString(ExpiresAfterFormat));
                else
                    writer.WriteNull("expiresAfter");

            if (outboundFileSet.PeriodOption.IsSet)
                if (outboundFileSet.PeriodOption.Value != null)
                    writer.WriteString("period", outboundFileSet.PeriodOption.Value!.Value.ToString(PeriodFormat));
                else
                    writer.WriteNull("period");
        }
    }

    /// <summary>
    /// The OutboundFileSetSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(OutboundFileSet))]
    public partial class OutboundFileSetSerializationContext : JsonSerializerContext { }
}
