/*
 * Copyright 2021 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Calcasa.Api.Api;
using Calcasa.Api.Model;
using Calcasa.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Calcasa.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Funderingdata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FunderingdataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Funderingdata
        //private Funderingdata instance;

        public FunderingdataTests()
        {
            // TODO uncomment below to create an instance of Funderingdata
            //instance = new Funderingdata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Funderingdata
        /// </summary>
        [Fact]
        public void FunderingdataInstanceTest()
        {
            // TODO uncomment below to test "IsType" Funderingdata
            //Assert.IsType<Funderingdata>(instance);
        }


        /// <summary>
        /// Test the property 'Typering'
        /// </summary>
        [Fact]
        public void TyperingTest()
        {
            // TODO unit test for the property 'Typering'
        }
        /// <summary>
        /// Test the property 'HerstelType'
        /// </summary>
        [Fact]
        public void HerstelTypeTest()
        {
            // TODO unit test for the property 'HerstelType'
        }
        /// <summary>
        /// Test the property 'DroogstandRisico'
        /// </summary>
        [Fact]
        public void DroogstandRisicoTest()
        {
            // TODO unit test for the property 'DroogstandRisico'
        }
        /// <summary>
        /// Test the property 'OptrekkendVochtRisico'
        /// </summary>
        [Fact]
        public void OptrekkendVochtRisicoTest()
        {
            // TODO unit test for the property 'OptrekkendVochtRisico'
        }
        /// <summary>
        /// Test the property 'BioInfectieRisico'
        /// </summary>
        [Fact]
        public void BioInfectieRisicoTest()
        {
            // TODO unit test for the property 'BioInfectieRisico'
        }
        /// <summary>
        /// Test the property 'Herstelkosten'
        /// </summary>
        [Fact]
        public void HerstelkostenTest()
        {
            // TODO unit test for the property 'Herstelkosten'
        }
        /// <summary>
        /// Test the property 'Bron'
        /// </summary>
        [Fact]
        public void BronTest()
        {
            // TODO unit test for the property 'Bron'
        }

    }

}
