/*
 * Copyright 2021 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Calcasa.Api.Api;
using Calcasa.Api.Model;
using Calcasa.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Calcasa.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Waardering
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WaarderingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Waardering
        //private Waardering instance;

        public WaarderingTests()
        {
            // TODO uncomment below to create an instance of Waardering
            //instance = new Waardering();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Waardering
        /// </summary>
        [Fact]
        public void WaarderingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Waardering
            //Assert.IsType<Waardering>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Aangemaakt'
        /// </summary>
        [Fact]
        public void AangemaaktTest()
        {
            // TODO unit test for the property 'Aangemaakt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'OrigineleInput'
        /// </summary>
        [Fact]
        public void OrigineleInputTest()
        {
            // TODO unit test for the property 'OrigineleInput'
        }
        /// <summary>
        /// Test the property 'Adres'
        /// </summary>
        [Fact]
        public void AdresTest()
        {
            // TODO unit test for the property 'Adres'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Taxatie'
        /// </summary>
        [Fact]
        public void TaxatieTest()
        {
            // TODO unit test for the property 'Taxatie'
        }
        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
        /// <summary>
        /// Test the property 'CbsIndeling'
        /// </summary>
        [Fact]
        public void CbsIndelingTest()
        {
            // TODO unit test for the property 'CbsIndeling'
        }
        /// <summary>
        /// Test the property 'Fotos'
        /// </summary>
        [Fact]
        public void FotosTest()
        {
            // TODO unit test for the property 'Fotos'
        }
        /// <summary>
        /// Test the property 'Referenties'
        /// </summary>
        [Fact]
        public void ReferentiesTest()
        {
            // TODO unit test for the property 'Referenties'
        }
        /// <summary>
        /// Test the property 'VorigeVerkopen'
        /// </summary>
        [Fact]
        public void VorigeVerkopenTest()
        {
            // TODO unit test for the property 'VorigeVerkopen'
        }
        /// <summary>
        /// Test the property 'Rapport'
        /// </summary>
        [Fact]
        public void RapportTest()
        {
            // TODO unit test for the property 'Rapport'
        }
        /// <summary>
        /// Test the property 'Factuur'
        /// </summary>
        [Fact]
        public void FactuurTest()
        {
            // TODO unit test for the property 'Factuur'
        }

    }

}
