/*
 * Copyright 2021 Calcasa B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Calcasa Public API
 *
 * The version of the OpenAPI document: v0
 * Contact: info@calcasa.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Calcasa.Api.Client;
using Calcasa.Api.Api;
// uncomment below to import models
//using Calcasa.Api.Model;

namespace Calcasa.Api.Test.Api
{
    /// <summary>
    ///  Class for testing AdressenApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdressenApiTests : IDisposable
    {
        private AdressenApi instance;

        public AdressenApiTests()
        {
            instance = new AdressenApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdressenApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdressenApi
            //Assert.IsType<AdressenApi>(instance);
        }

        /// <summary>
        /// Test GetAdres
        /// </summary>
        [Fact]
        public void GetAdresTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long bagNummeraanduidingId = null;
            //var response = instance.GetAdres(bagNummeraanduidingId);
            //Assert.IsType<AdresInfo>(response);
        }

        /// <summary>
        /// Test SearchAdres
        /// </summary>
        [Fact]
        public void SearchAdresTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Adres adres = null;
            //var response = instance.SearchAdres(adres);
            //Assert.IsType<AdresInfo>(response);
        }
    }
}
